import './globals.css';
import { Inter } from 'next/font/google';
import './components/subComponents/ModalContactUs/ModalContactUs.module.css';
import { IdeaContextProvider } from './context/AppContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<IdeaContextProvider>{children}</IdeaContextProvider>
			</body>
		</html>
	);
}
